# Generated by Django 3.2.7 on 2021-09-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(null=True, verbose_name='Album description'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(null=True, verbose_name='Artist description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(null=True, verbose_name='Genre description'),
        ),
    ]
