# Generated by Django 3.2.7 on 2021-09-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs_app.genre', verbose_name='genre'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='year',
            field=models.IntegerField(default=2021, verbose_name='Album release year'),
        ),
    ]
