# Generated by Django 3.2.7 on 2021-09-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0002_auto_20210924_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(default='no description', verbose_name='Album description'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(default='no description', verbose_name='Artist description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(default='no description', verbose_name='Genre description'),
        ),
    ]
